/* Generated by Together */

package de.ivu.ejb.bmp;

import java.io.Serializable;

public interface Model extends Serializable {
  /**
   * Function returns <code>true</code> if the data of the model was changed
   */
  public boolean isModified();

  /**
   * Function sets the state to "modified".
   */
  public void setModified();
}
